// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pb/user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	KycStatusId   int64                  `protobuf:"varint,4,opt,name=kyc_status_id,json=kycStatusId,proto3" json:"kyc_status_id,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_pb_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_pb_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_pb_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetKycStatusId() int64 {
	if x != nil {
		return x.KycStatusId
	}
	return 0
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type SessionUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	KycStatusId   int64                  `protobuf:"varint,2,opt,name=kyc_status_id,json=kycStatusId,proto3" json:"kyc_status_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionUser) Reset() {
	*x = SessionUser{}
	mi := &file_pb_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionUser) ProtoMessage() {}

func (x *SessionUser) ProtoReflect() protoreflect.Message {
	mi := &file_pb_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionUser.ProtoReflect.Descriptor instead.
func (*SessionUser) Descriptor() ([]byte, []int) {
	return file_pb_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *SessionUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SessionUser) GetKycStatusId() int64 {
	if x != nil {
		return x.KycStatusId
	}
	return 0
}

type GetUserByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIDRequest) Reset() {
	*x = GetUserByIDRequest{}
	mi := &file_pb_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIDRequest) ProtoMessage() {}

func (x *GetUserByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIDRequest) Descriptor() ([]byte, []int) {
	return file_pb_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserByIDRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIDResponse) Reset() {
	*x = GetUserByIDResponse{}
	mi := &file_pb_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIDResponse) ProtoMessage() {}

func (x *GetUserByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIDResponse.ProtoReflect.Descriptor instead.
func (*GetUserByIDResponse) Descriptor() ([]byte, []int) {
	return file_pb_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserByIDResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ValidateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSessionRequest) Reset() {
	*x = ValidateSessionRequest{}
	mi := &file_pb_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSessionRequest) ProtoMessage() {}

func (x *ValidateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSessionRequest.ProtoReflect.Descriptor instead.
func (*ValidateSessionRequest) Descriptor() ([]byte, []int) {
	return file_pb_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateSessionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *SessionUser           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSessionResponse) Reset() {
	*x = ValidateSessionResponse{}
	mi := &file_pb_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSessionResponse) ProtoMessage() {}

func (x *ValidateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSessionResponse.ProtoReflect.Descriptor instead.
func (*ValidateSessionResponse) Descriptor() ([]byte, []int) {
	return file_pb_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateSessionResponse) GetUser() *SessionUser {
	if x != nil {
		return x.User
	}
	return nil
}

var File_pb_user_user_proto protoreflect.FileDescriptor

const file_pb_user_user_proto_rawDesc = "" +
	"\n" +
	"\x12pb/user/user.proto\x12\x04user\"x\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\"\n" +
	"\rkyc_status_id\x18\x04 \x01(\x03R\vkycStatusId\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\"A\n" +
	"\vSessionUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\"\n" +
	"\rkyc_status_id\x18\x02 \x01(\x03R\vkycStatusId\"-\n" +
	"\x12GetUserByIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"5\n" +
	"\x13GetUserByIDResponse\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".user.UserR\x04user\".\n" +
	"\x16ValidateSessionRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"@\n" +
	"\x17ValidateSessionResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.user.SessionUserR\x04user2\xa1\x01\n" +
	"\vUserService\x12B\n" +
	"\vGetUserByID\x12\x18.user.GetUserByIDRequest\x1a\x19.user.GetUserByIDResponse\x12N\n" +
	"\x0fValidateSession\x12\x1c.user.ValidateSessionRequest\x1a\x1d.user.ValidateSessionResponseB1Z/github.com/tubagusmf/tbwallet-user-auth/pb/userb\x06proto3"

var (
	file_pb_user_user_proto_rawDescOnce sync.Once
	file_pb_user_user_proto_rawDescData []byte
)

func file_pb_user_user_proto_rawDescGZIP() []byte {
	file_pb_user_user_proto_rawDescOnce.Do(func() {
		file_pb_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_user_user_proto_rawDesc), len(file_pb_user_user_proto_rawDesc)))
	})
	return file_pb_user_user_proto_rawDescData
}

var file_pb_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_user_user_proto_goTypes = []any{
	(*User)(nil),                    // 0: user.User
	(*SessionUser)(nil),             // 1: user.SessionUser
	(*GetUserByIDRequest)(nil),      // 2: user.GetUserByIDRequest
	(*GetUserByIDResponse)(nil),     // 3: user.GetUserByIDResponse
	(*ValidateSessionRequest)(nil),  // 4: user.ValidateSessionRequest
	(*ValidateSessionResponse)(nil), // 5: user.ValidateSessionResponse
}
var file_pb_user_user_proto_depIdxs = []int32{
	0, // 0: user.GetUserByIDResponse.user:type_name -> user.User
	1, // 1: user.ValidateSessionResponse.user:type_name -> user.SessionUser
	2, // 2: user.UserService.GetUserByID:input_type -> user.GetUserByIDRequest
	4, // 3: user.UserService.ValidateSession:input_type -> user.ValidateSessionRequest
	3, // 4: user.UserService.GetUserByID:output_type -> user.GetUserByIDResponse
	5, // 5: user.UserService.ValidateSession:output_type -> user.ValidateSessionResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_user_user_proto_init() }
func file_pb_user_user_proto_init() {
	if File_pb_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_user_user_proto_rawDesc), len(file_pb_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_user_user_proto_goTypes,
		DependencyIndexes: file_pb_user_user_proto_depIdxs,
		MessageInfos:      file_pb_user_user_proto_msgTypes,
	}.Build()
	File_pb_user_user_proto = out.File
	file_pb_user_user_proto_goTypes = nil
	file_pb_user_user_proto_depIdxs = nil
}
