// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pb/kycdoc/kycdoc.proto

package kycdoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kycdoc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DocumentType  string                 `protobuf:"bytes,3,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"`
	DocumentUrl   string                 `protobuf:"bytes,4,opt,name=document_url,json=documentUrl,proto3" json:"document_url,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kycdoc) Reset() {
	*x = Kycdoc{}
	mi := &file_pb_kycdoc_kycdoc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kycdoc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kycdoc) ProtoMessage() {}

func (x *Kycdoc) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kycdoc_kycdoc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kycdoc.ProtoReflect.Descriptor instead.
func (*Kycdoc) Descriptor() ([]byte, []int) {
	return file_pb_kycdoc_kycdoc_proto_rawDescGZIP(), []int{0}
}

func (x *Kycdoc) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Kycdoc) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Kycdoc) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *Kycdoc) GetDocumentUrl() string {
	if x != nil {
		return x.DocumentUrl
	}
	return ""
}

func (x *Kycdoc) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetKycdocByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKycdocByUserIDRequest) Reset() {
	*x = GetKycdocByUserIDRequest{}
	mi := &file_pb_kycdoc_kycdoc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKycdocByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKycdocByUserIDRequest) ProtoMessage() {}

func (x *GetKycdocByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kycdoc_kycdoc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKycdocByUserIDRequest.ProtoReflect.Descriptor instead.
func (*GetKycdocByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_pb_kycdoc_kycdoc_proto_rawDescGZIP(), []int{1}
}

func (x *GetKycdocByUserIDRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetKycdocByUserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kycdocs       []*Kycdoc              `protobuf:"bytes,1,rep,name=kycdocs,proto3" json:"kycdocs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKycdocByUserIDResponse) Reset() {
	*x = GetKycdocByUserIDResponse{}
	mi := &file_pb_kycdoc_kycdoc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKycdocByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKycdocByUserIDResponse) ProtoMessage() {}

func (x *GetKycdocByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kycdoc_kycdoc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKycdocByUserIDResponse.ProtoReflect.Descriptor instead.
func (*GetKycdocByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_pb_kycdoc_kycdoc_proto_rawDescGZIP(), []int{2}
}

func (x *GetKycdocByUserIDResponse) GetKycdocs() []*Kycdoc {
	if x != nil {
		return x.Kycdocs
	}
	return nil
}

type GetKycStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKycStatusRequest) Reset() {
	*x = GetKycStatusRequest{}
	mi := &file_pb_kycdoc_kycdoc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKycStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKycStatusRequest) ProtoMessage() {}

func (x *GetKycStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kycdoc_kycdoc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKycStatusRequest.ProtoReflect.Descriptor instead.
func (*GetKycStatusRequest) Descriptor() ([]byte, []int) {
	return file_pb_kycdoc_kycdoc_proto_rawDescGZIP(), []int{3}
}

func (x *GetKycStatusRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetKycStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKycStatusResponse) Reset() {
	*x = GetKycStatusResponse{}
	mi := &file_pb_kycdoc_kycdoc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKycStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKycStatusResponse) ProtoMessage() {}

func (x *GetKycStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kycdoc_kycdoc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKycStatusResponse.ProtoReflect.Descriptor instead.
func (*GetKycStatusResponse) Descriptor() ([]byte, []int) {
	return file_pb_kycdoc_kycdoc_proto_rawDescGZIP(), []int{4}
}

func (x *GetKycStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_pb_kycdoc_kycdoc_proto protoreflect.FileDescriptor

const file_pb_kycdoc_kycdoc_proto_rawDesc = "" +
	"\n" +
	"\x16pb/kycdoc/kycdoc.proto\x12\x06kycdoc\"\x91\x01\n" +
	"\x06Kycdoc\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12#\n" +
	"\rdocument_type\x18\x03 \x01(\tR\fdocumentType\x12!\n" +
	"\fdocument_url\x18\x04 \x01(\tR\vdocumentUrl\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"3\n" +
	"\x18GetKycdocByUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"E\n" +
	"\x19GetKycdocByUserIDResponse\x12(\n" +
	"\akycdocs\x18\x01 \x03(\v2\x0e.kycdoc.KycdocR\akycdocs\".\n" +
	"\x13GetKycStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\".\n" +
	"\x14GetKycStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xb4\x01\n" +
	"\rKycdocService\x12X\n" +
	"\x11GetKycdocByUserID\x12 .kycdoc.GetKycdocByUserIDRequest\x1a!.kycdoc.GetKycdocByUserIDResponse\x12I\n" +
	"\fGetKycStatus\x12\x1b.kycdoc.GetKycStatusRequest\x1a\x1c.kycdoc.GetKycStatusResponseB3Z1github.com/tubagusmf/tbwallet-user-auth/pb/kycdocb\x06proto3"

var (
	file_pb_kycdoc_kycdoc_proto_rawDescOnce sync.Once
	file_pb_kycdoc_kycdoc_proto_rawDescData []byte
)

func file_pb_kycdoc_kycdoc_proto_rawDescGZIP() []byte {
	file_pb_kycdoc_kycdoc_proto_rawDescOnce.Do(func() {
		file_pb_kycdoc_kycdoc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_kycdoc_kycdoc_proto_rawDesc), len(file_pb_kycdoc_kycdoc_proto_rawDesc)))
	})
	return file_pb_kycdoc_kycdoc_proto_rawDescData
}

var file_pb_kycdoc_kycdoc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_kycdoc_kycdoc_proto_goTypes = []any{
	(*Kycdoc)(nil),                    // 0: kycdoc.Kycdoc
	(*GetKycdocByUserIDRequest)(nil),  // 1: kycdoc.GetKycdocByUserIDRequest
	(*GetKycdocByUserIDResponse)(nil), // 2: kycdoc.GetKycdocByUserIDResponse
	(*GetKycStatusRequest)(nil),       // 3: kycdoc.GetKycStatusRequest
	(*GetKycStatusResponse)(nil),      // 4: kycdoc.GetKycStatusResponse
}
var file_pb_kycdoc_kycdoc_proto_depIdxs = []int32{
	0, // 0: kycdoc.GetKycdocByUserIDResponse.kycdocs:type_name -> kycdoc.Kycdoc
	1, // 1: kycdoc.KycdocService.GetKycdocByUserID:input_type -> kycdoc.GetKycdocByUserIDRequest
	3, // 2: kycdoc.KycdocService.GetKycStatus:input_type -> kycdoc.GetKycStatusRequest
	2, // 3: kycdoc.KycdocService.GetKycdocByUserID:output_type -> kycdoc.GetKycdocByUserIDResponse
	4, // 4: kycdoc.KycdocService.GetKycStatus:output_type -> kycdoc.GetKycStatusResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_kycdoc_kycdoc_proto_init() }
func file_pb_kycdoc_kycdoc_proto_init() {
	if File_pb_kycdoc_kycdoc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_kycdoc_kycdoc_proto_rawDesc), len(file_pb_kycdoc_kycdoc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_kycdoc_kycdoc_proto_goTypes,
		DependencyIndexes: file_pb_kycdoc_kycdoc_proto_depIdxs,
		MessageInfos:      file_pb_kycdoc_kycdoc_proto_msgTypes,
	}.Build()
	File_pb_kycdoc_kycdoc_proto = out.File
	file_pb_kycdoc_kycdoc_proto_goTypes = nil
	file_pb_kycdoc_kycdoc_proto_depIdxs = nil
}
